version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Nemo157
  assignees:
  - Nemo157
  ignore:
  - dependency-name: anyhow
    versions:
    - 1.0.38
    - 1.0.39
